import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import data from '../data/Data.json';
// import { SlideData } from '../data/SlideData';
// import { Links } from '../data/Links';
// import { FAQData } from '../data/FAQData';

import Header from '../components/Header';
import Snipe from '../components/Snipe';
import Slider from '../components/Slider';
import FAQ from '../components/FAQ';
import Footer from '../components/Footer';

export default function Home(props) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Aim Lab Mobile | Join The Public Beta</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Snipe title={'Play for free'} />
			<Header
				image={props.image}
				altText={props.altText}
				title={'Improve your aim now'}
				links={props.badgeLinks}
			/>
			<Slider slideData={props.slideData} />
			<FAQ title={'Frequently Asked Questions'} faqData={props.faqData} />
			<Footer />
		</div>
	);
}

// SSR
export async function getStaticProps() {
	return {
		props: {
			badgeLinks: data[0].badgeLinks,
			image: data[0].logos,
			altText: data[0].altText,
			slideData: data[0].slideData,
			faqData: data[0].faqData,
		},
		// Validate data every X seconds once built - prevent serving outdated data once deployed
		revalidate: 3600,
	};
}
