import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { images } from '../public/images/index';
import { SlideData } from '../data/SlideData';
import { Links } from '../data/Links';
import { FAQData } from '../data/FAQData';

import Header from '../components/Header';
import Snipe from '../components/Snipe';
import Slider from '../components/Slider';
import FAQ from '../components/FAQ';
import Footer from '../components/Footer';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Aim Lab Mobile | Join The Public Beta</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Snipe title={'Play for free'} />
			<Header image={images} title={'Improve your aim now'} links={Links} />
			<Slider slides={SlideData} />
			<FAQ title={'Frequently Asked Questions'} data={FAQData} />
			<Footer />
		</div>
	);
}
